routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);
Route::group(['middleware' => ['auth']], function () {
Route::post('email/resend', 'Auth\VerificationController@resend');
});
/////// Admin ///
Route::group(['middleware' => ['auth']], function () {
    Route::post('logout', 'Auth\AuthController@logout')->name('logout');
});

Route::get('login', 'Auth\AuthController@showLoginForm')->name('loginForm');
Route::post('login', 'Auth\AuthController@login')->name('login');
Route::group(['namespace' => 'Back', 'middleware' => ['verified', 'auth']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('/profile', 'UserController@getUpdateProfile')->name('get-update-profile');
    Route::patch('/profile', 'UserController@postUpdateProfile')->name('post-update-profile');
    //
    Route::group(['middleware' => ['permission:users|admin', 'MinifyHtml']], function () {
        Route::resource('users', 'UserController');
    });
    Route::group(['middleware' => ['permission:roles|admin', 'MinifyHtml']], function () {
        Route::resource('roles', 'RoleController');
    });
    Route::group(['middleware' => ['permission:permissions|admin', 'MinifyHtml']], function () {
        Route::resource('permissions', 'PermissionController');
    });
    Route::group(['middleware' => ['permission:sales|admin']], function () {
        Route::resource('sales', 'SalesController');

    });
    Route::group(['middleware' => ['permission:configrations|admin']], function () {
        Route::resource('configrations', 'ConfigrationsController');

    });

    Route::group(['middleware' => ['permission:settings|admin']], function () {
        Route::get('setting', 'SettingController@index')->name('setting.index');
        Route::post('setting', 'SettingController@update')->name('setting.update');
    });
});

app/Http/Controllers/Back/ConfigrationsController.php
<?php

namespace App\Http\Controllers\Back;


use App\Http\Controllers\Controller;

use App\Configration as Model;


class ConfigrationsController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $configrations = Model::paginate();

        return view('back.configrations.index')->with('configrations', $configrations);
    }


}

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\AbstractSubmission;
use App\FullSubmission;
use App\Register;
use Validator;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;
use DB;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {

    }
    public function index()
    {
        $sales = DB::table('sales')->where('deleted_at',null)->count();
        $users = DB::table('users')->where('deleted_at',null)->count();
        return view('back.dashboard.index',compact('users','sales'));
    }

}

app/Http/Controllers/Back/PermissionController.php
<?php

namespace App\Http\Controllers\Back;

use Illuminate\Http\Request;

use Auth;
use App\Http\Controllers\Controller;

//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use Session;

class PermissionController extends Controller {

    public function __construct() {
        $this->middleware(['auth']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $permissions = Permission::all(); //Get all permissions

        return view('back.permissions.index')->with('permissions', $permissions);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $roles = Role::get(); //Get all roles

        return view('back.permissions.create')->with('roles', $roles);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);

        $name = $request['name'];
        $permission = new Permission();
        $permission->name = $name;

        $roles = $request['roles'];

        $permission->save();

        if (!empty($request['roles'])) { //If one or more role is selected
            foreach ($roles as $role) {
                $r = Role::where('id', '=', $role)->firstOrFail(); //Match input role to db record

                $permission = Permission::where('name', '=', $name)->first(); //Match input //permission to db record
                $r->givePermissionTo($permission);
            }
        }

        return redirect()->route('permissions.index')
            ->with('flash_message',
                'Permission'. $permission->name.' added!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        return redirect('permissions');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $permission = Permission::find($id);
        if(!$permission)
        {
            abort(404);
        }
        return view('back.permissions.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $permission = Permission::find($id);
        if(!$permission)
        {
            abort(404);
        }
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);
        $input = $request->all();
        $permission->fill($input)->save();

        return redirect()->route('permissions.index')
            ->with('flash_message',
                'Permission'. $permission->name.' updated!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $permission = Permission::find($id);
        if(!$permission)
        {
            abort(404);
        }
        //Make it impossible to delete this specific permission
        if ($permission->name == "Administer roles & permissions") {
            return redirect()->route('permissions.index')
                ->with('flash_message',
                    'Cannot delete this Permission!');
        }

        $permission->delete();

        return redirect()->route('permissions.index')
            ->with('flash_message',
                'Permission deleted!');

    }
}

app/Http/Controllers/Back/RoleController.php
<?php

namespace App\Http\Controllers\Back;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Auth;
//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use Session;

class RoleController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth']);//isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();//Get all roles

        return view('back.roles.index')->with('roles', $roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all();//Get all permissions

        return view('back.roles.create', ['permissions' => $permissions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validate name and permissions field
        $this->validate($request, [
                'name' => 'required|unique:roles|max:30',
                'permissions' => 'required',
            ]
        );

        $name = $request['name'];
        $role = new Role();
        $role->name = $name;

        $permissions = $request['permissions'];

        $role->save();
        //Looping thru selected permissions
        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail();
            //Fetch the newly created role and assign permission
            $role = Role::where('name', '=', $name)->first();
            $role->givePermissionTo($p);
        }

        return redirect()->route('roles.index')
            ->with('flash_message',
                'Role' . $role->name . ' added!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect('roles');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::findOrFail($id);
        $permissions = Permission::all();

        return view('back.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $role = Role::findOrFail($id);//Get role with the given id
        //Validate name and permission fields
        $this->validate($request, [
            'name' => 'required|max:30|unique:roles,name,' . $id,
            'permissions' => 'required',
        ]);

        $input = $request->except(['permissions']);
        $permissions = $request['permissions'];
//        dd($input);
        $role->fill(['name'=>$input['name']])->save();

        $p_all = Permission::all();//Get all permissions

        foreach ($p_all as $p) {
            $role->revokePermissionTo($p); //Remove all permissions associated with role
        }

        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
            $role->givePermissionTo($p);  //Assign permission to role
        }

        return redirect()->route('roles.index')
            ->with('flash_message',
                'Role' . $role->name . ' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);

        if ($role->name == 'admin' || $role->users()->count()>=0) {
            return redirect()->route('roles.index')
                ->with('flash_message',
                    "Can't delete this permisson!");
        }
        $role->delete();

        return redirect()->route('roles.index')
            ->with('flash_message',
                'Role deleted!');

    }
}

app/Http/Controllers/Back/SalesController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Salesman as Model;

class SalesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sales = Model::paginate();

        return view('back.sales.index')->with('sales', $sales);
    }
}

app/Http/Controllers/Back/SettingController.php
<?php

namespace App\Http\Controllers\Back;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class SettingController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth']); //isAdmin middleware lets only users with a //specific permission permission to access these resources

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $setting = \Setting::all(); //Get all permission
        return view('back.settings.index')->with('setting', $setting);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $array = $request->all();
        // remove token
        unset($array['_token']);
       // validation
        $this->validate($request, [
            'logo' => 'file|mimes:png|max:20000',
            'link' => 'url',
        ]);

        // settings

        if ($request->logo) {

            $fileName_ar = 'logo-white.' . request()->logo->getClientOriginalExtension();
            request()->logo->move(public_path('back/assets/global/images/logo/'), $fileName_ar);
            $array['logo'] = $fileName_ar;
        }
        // remove item null
        foreach ($array as $k => $ar) {
            if (!$ar)
                unset($array[$k]);
        }
        setting($array)->save();
        return redirect()->route('setting.index')
            ->with('flash_message',
                'Settings saved');
    }

}

resources/views/back/parts/file.blade.php
<div class='col-lg-2' style="margin-left: 10px;">
    <div class="form-group">
        @if($image->type=='img')
            <img style="width: 150px;display: inline-block" src="/products_view/{{$image->url}}">
            <a class="boxclose" href="{{route('product.delete.image',[$image->id,$product->id])}}"></a>
        @elseif($image->type=='video')
            <video width="150" controls>
                <source src="/files/{{$image->url}}" type="video/mp4">
                <source src="/files/{{$image->url}}" type="video/ogg">
                Your browser does not support the video tag.
            </video>
            <a class="boxclose" href="{{route('product.delete.image',[$image->id,$product->id])}}"></a>
        @endif
    </div>
</div>

resources/views/back/parts/search.blade.php
<div id="morphsearch" class="morphsearch">
    <form class="morphsearch-form">
        <input class="morphsearch-input" type="search" placeholder="Search..."/>
        <button class="morphsearch-submit" type="submit">Search</button>
    </form>
    <div class="morphsearch-content withScroll">
        <div class="dummy-column user-column">
            <h2>Users</h2>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/avatars/avatar1_big.png')}}" alt="Avatar 1"/>
                <h3>John Smith</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/avatars/avatar2_big.png')}}" alt="Avatar 2"/>
                <h3>Bod Dylan</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/avatars/avatar3_big.png')}}" alt="Avatar 3"/>
                <h3>Jenny Finlan</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/avatars/avatar4_big.png')}}" alt="Avatar 4"/>
                <h3>Harold Fox</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/avatars/avatar5_big.png')}}" alt="Avatar 5"/>
                <h3>Martin Hendrix</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/avatars/avatar6_big.png')}}" alt="Avatar 6"/>
                <h3>Paul Ferguson</h3>
            </a>
        </div>
        <div class="dummy-column">
            <h2>Articles</h2>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/gallery/1.jpg')}}" alt="1"/>
                <h3>How to change webdesign?</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/gallery/2.jpg')}}" alt="2"/>
                <h3>News From the sky</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/gallery/3.jpg')}}" alt="3"/>
                <h3>Where is the cat?</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/gallery/4.jpg')}}" alt="4"/>
                <h3>Just another funny story</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/gallery/5.jpg')}}" alt="5"/>
                <h3>How many water we drink every day?</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/gallery/6.jpg')}}" alt="6"/>
                <h3>Drag and drop tutorials</h3>
            </a>
        </div>
        <div class="dummy-column">
            <h2>Recent</h2>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/gallery/7.jpg')}}" alt="7"/>
                <h3>Design Inspiration</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/gallery/8.jpg')}}" alt="8"/>
                <h3>Animals drawing</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/gallery/9.jpg')}}" alt="9"/>
                <h3>Cup of tea please</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/gallery/10.jpg')}}" alt="10"/>
                <h3>New application arrive</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/gallery/11.jpg')}}" alt="11"/>
                <h3>Notification prettify</h3>
            </a>
            <a class="dummy-media-object" href="#">
                <img src="{{asset('back/assets/global/images/gallery/12.jpg')}}" alt="12"/>
                <h3>My article is the last recent</h3>
            </a>
        </div>
    </div>
    <!-- /morphsearch-content -->
    <span class="morphsearch-close"></span>
</div>
<!-- END SEARCH -->
<!-- BEGIN PRELOADER -->
<div class="loader-overlay">
    <div class="spinner">
        <div class="bounce1"></div>
        <div class="bounce2"></div>
        <div class="bounce3"></div>
    </div>
</div>
<!-- END PRELOADER -->

resources/views/back/parts/sidebar.blade.php
<div class="sidebar">
    <div class="logopanel">
        <h1>
            <a href="/"></a>
        </h1>
    </div>
    <div class="sidebar-inner">
        <div class="sidebar-top">
            {{--            <form action="#" method="post" class="searchform" id="search">--}}
            {{--                <input type="text" class="form-control" name="keyword" placeholder="Search...">--}}
            {{--            </form>--}}
            <div class="userlogged clearfix">
                <img style="width:70px;float: left"
                     src="{{asset((is_null(Auth::user()->image))?'/avatar/user1.png':'/avatar/'.Auth::user()->image->url)}}"
                     alt="user image">
                <div class="user-details">
                    <h4>{{Auth::user()->name}}</h4>
                    <div class="dropdown user-login">
                        <button class="btn btn-xs dropdown-toggle btn-rounded" type="button" data-toggle="dropdown"
                                data-hover="dropdown" data-close-others="true" data-delay="300">
                            <i class="online"></i><span>Available</span><i class="fa fa-angle-down"></i>
                        </button>
                        {{--                        <ul class="dropdown-menu">--}}
                        {{--                            <li><a href="#"><i class="busy"></i><span>Busy</span></a></li>--}}
                        {{--                            <li><a href="#"><i class="turquoise"></i><span>Invisible</span></a></li>--}}
                        {{--                            <li><a href="#"><i class="away"></i><span>Away</span></a></li>--}}
                        {{--                        </ul>--}}
                    </div>
                </div>

            </div>
        </div>
        <div class="menu-title">
            <div class="pull-right menu-settings">
                {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" data-delay="300">--}}
                {{--<i class="icon-settings"></i>--}}
                {{--</a>--}}
                <ul class="dropdown-menu">
                    <li><a href="#" id="reorder-menu" class="reorder-menu">Reorder menu</a></li>
                    <li><a href="#" id="remove-menu" class="remove-menu">Remove elements</a></li>
                    <li><a href="#" id="hide-top-sidebar" class="hide-top-sidebar">Hide user &amp; search</a></li>
                </ul>
            </div>
        </div>
        <ul class="nav nav-sidebar">
            <li class="nav-active"><a href="{{route('dashboard')}}"><i class="icon-home"></i><span>Dashboard</span></a>
            </li>
            @can('users')
                <li class="nav-active"><a href="{{route('users.index')}}"><i
                            class="fa fa-user"></i><span>Users</span></a>
                </li>
                {{--<li class="nav-active"><a href="{{route('payment-link')}}"><i class="icon-home"></i><span>Send Link Payment</span></a></li>--}}
            @endcan
            @can('roles')
                <li class="nav-active"><a href="{{route('roles.index')}}"><i
                            class="fa fa-lock"></i><span>Roles</span></a>
                </li>
            @endcan

            @can('sales')
                <li class="nav-active"><a href="{{route('sales.index')}}"><i
                            class="fa fa-archive"></i><span>sales</span></a></li>
            @endcan
            @can('configrations')
            <li class="nav-active"><a href="{{route('configrations.index')}}"><i
                            class="fa fa-archive"></i><span>configrations</span></a></li>
            @endcan
            @can('settings')
                <li class="nav-active"><a href="{{route('setting.index')}}"><i
                            class="fa fa-history"></i><span>Settings</span></a></li>
            @endcan

        </ul>

        <div class="sidebar-footer clearfix">

            <a class="pull-left toggle_fullscreen" data-rel="tooltip" data-placement="top"
               data-original-title="Fullscreen">
                <i class="icon-size-fullscreen"></i></a>

            <form method="post" action="{{route('logout')}}" style="display: block">
                {{ csrf_field() }}
                <a class="pull-left btn-effect" href="#" data-modal="modal-1" data-rel="tooltip" data-placement="top"
                   data-original-title="Logout" onclick='this.parentNode.submit(); return false;'>
                    <i class="icon-power"></i></a>
            </form>
        </div>
    </div>
</div>