routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);
Route::group(['middleware' => ['auth']], function () {
Route::post('email/resend', 'Auth\VerificationController@resend');
});
/////// Admin ///
Route::group(['middleware' => ['auth']], function () {
    Route::post('logout', 'Auth\AuthController@logout')->name('logout');
});

Route::get('login', 'Auth\AuthController@showLoginForm')->name('loginForm');
Route::post('login', 'Auth\AuthController@login')->name('login');
Route::group(['namespace' => 'Back', 'middleware' => ['verified', 'auth']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('/profile', 'UserController@getUpdateProfile')->name('get-update-profile');
    Route::patch('/profile', 'UserController@postUpdateProfile')->name('post-update-profile');
    //
    Route::group(['middleware' => ['permission:users|admin', 'MinifyHtml']], function () {
        Route::resource('users', 'UserController');
    });
    Route::group(['middleware' => ['permission:roles|admin', 'MinifyHtml']], function () {
        Route::resource('roles', 'RoleController');
    });
    Route::group(['middleware' => ['permission:permissions|admin', 'MinifyHtml']], function () {
        Route::resource('permissions', 'PermissionController');
    });
    Route::group(['middleware' => ['permission:sales|admin']], function () {
        Route::resource('sales', 'SalesController');

    });
    Route::group(['middleware' => ['permission:configrations|admin']], function () {
        Route::resource('configrations', 'ConfigrationsController');

    });

    Route::group(['middleware' => ['permission:settings|admin']], function () {
        Route::get('setting', 'SettingController@index')->name('setting.index');
        Route::post('setting', 'SettingController@update')->name('setting.update');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, HasRoles, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];
    public $path_files = 'avatar/';
    protected $fillable = [
        'name', 'email', 'password','website'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function image()
    {
        return $this->morphOne('App\File', 'imageable');
    }

    public function uploadFile()
    {
        // upload file ar file
        $file = (!$this->image) ? new File() : File::find($this->image->id);
        if (request()->avatar) {
            $fileName = time() . '.' . request()->avatar->getClientOriginalExtension();
            $file->setTranslation('url', 'en', $fileName);
            $file->setTranslation('url', 'ar', $fileName);
            @unlink($this->path_files . @$this->image->translations['url']['ar']);
            request()->avatar->move($this->path_files, $fileName);
        }
        $file->type = 'img';
        (!$this->image) ? $file->save() : $file->update();
        return $file;
    }

    public function scopeNotSuperAdmin($q)
    {
        return $q->where('super_admin', '!=', 1);
    }
}

app/Http/Controllers/Back/ConfigrationsController.php
<?php

namespace App\Http\Controllers\Back;


use App\Http\Controllers\Controller;

use App\Configration as Model;


class ConfigrationsController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $configrations = Model::paginate();

        return view('back.configrations.index')->with('configrations', $configrations);
    }


}

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\AbstractSubmission;
use App\FullSubmission;
use App\Register;
use Validator;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;
use DB;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {

    }
    public function index()
    {
        $sales = DB::table('sales')->where('deleted_at',null)->count();
        $users = DB::table('users')->where('deleted_at',null)->count();
        return view('back.dashboard.index',compact('users','sales'));
    }

}

app/Http/Controllers/Back/PermissionController.php
<?php

namespace App\Http\Controllers\Back;

use Illuminate\Http\Request;

use Auth;
use App\Http\Controllers\Controller;

//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use Session;

class PermissionController extends Controller {

    public function __construct() {
        $this->middleware(['auth']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $permissions = Permission::all(); //Get all permissions

        return view('back.permissions.index')->with('permissions', $permissions);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $roles = Role::get(); //Get all roles

        return view('back.permissions.create')->with('roles', $roles);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);

        $name = $request['name'];
        $permission = new Permission();
        $permission->name = $name;

        $roles = $request['roles'];

        $permission->save();

        if (!empty($request['roles'])) { //If one or more role is selected
            foreach ($roles as $role) {
                $r = Role::where('id', '=', $role)->firstOrFail(); //Match input role to db record

                $permission = Permission::where('name', '=', $name)->first(); //Match input //permission to db record
                $r->givePermissionTo($permission);
            }
        }

        return redirect()->route('permissions.index')
            ->with('flash_message',
                'Permission'. $permission->name.' added!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        return redirect('permissions');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $permission = Permission::find($id);
        if(!$permission)
        {
            abort(404);
        }
        return view('back.permissions.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $permission = Permission::find($id);
        if(!$permission)
        {
            abort(404);
        }
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);
        $input = $request->all();
        $permission->fill($input)->save();

        return redirect()->route('permissions.index')
            ->with('flash_message',
                'Permission'. $permission->name.' updated!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $permission = Permission::find($id);
        if(!$permission)
        {
            abort(404);
        }
        //Make it impossible to delete this specific permission
        if ($permission->name == "Administer roles & permissions") {
            return redirect()->route('permissions.index')
                ->with('flash_message',
                    'Cannot delete this Permission!');
        }

        $permission->delete();

        return redirect()->route('permissions.index')
            ->with('flash_message',
                'Permission deleted!');

    }
}

app/Http/Controllers/Back/RoleController.php
<?php

namespace App\Http\Controllers\Back;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Auth;
//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use Session;

class RoleController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth']);//isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();//Get all roles

        return view('back.roles.index')->with('roles', $roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all();//Get all permissions

        return view('back.roles.create', ['permissions' => $permissions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validate name and permissions field
        $this->validate($request, [
                'name' => 'required|unique:roles|max:30',
                'permissions' => 'required',
            ]
        );

        $name = $request['name'];
        $role = new Role();
        $role->name = $name;

        $permissions = $request['permissions'];

        $role->save();
        //Looping thru selected permissions
        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail();
            //Fetch the newly created role and assign permission
            $role = Role::where('name', '=', $name)->first();
            $role->givePermissionTo($p);
        }

        return redirect()->route('roles.index')
            ->with('flash_message',
                'Role' . $role->name . ' added!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect('roles');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::findOrFail($id);
        $permissions = Permission::all();

        return view('back.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $role = Role::findOrFail($id);//Get role with the given id
        //Validate name and permission fields
        $this->validate($request, [
            'name' => 'required|max:30|unique:roles,name,' . $id,
            'permissions' => 'required',
        ]);

        $input = $request->except(['permissions']);
        $permissions = $request['permissions'];
//        dd($input);
        $role->fill(['name'=>$input['name']])->save();

        $p_all = Permission::all();//Get all permissions

        foreach ($p_all as $p) {
            $role->revokePermissionTo($p); //Remove all permissions associated with role
        }

        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
            $role->givePermissionTo($p);  //Assign permission to role
        }

        return redirect()->route('roles.index')
            ->with('flash_message',
                'Role' . $role->name . ' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);

        if ($role->name == 'admin' || $role->users()->count()>=0) {
            return redirect()->route('roles.index')
                ->with('flash_message',
                    "Can't delete this permisson!");
        }
        $role->delete();

        return redirect()->route('roles.index')
            ->with('flash_message',
                'Role deleted!');

    }
}

app/Http/Controllers/Back/SalesController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Salesman as Model;

class SalesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sales = Model::paginate();

        return view('back.sales.index')->with('sales', $sales);
    }
}

app/Http/Controllers/Back/SettingController.php
<?php

namespace App\Http\Controllers\Back;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class SettingController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth']); //isAdmin middleware lets only users with a //specific permission permission to access these resources

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $setting = \Setting::all(); //Get all permission
        return view('back.settings.index')->with('setting', $setting);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $array = $request->all();
        // remove token
        unset($array['_token']);
       // validation
        $this->validate($request, [
            'logo' => 'file|mimes:png|max:20000',
            'link' => 'url',
        ]);

        // settings

        if ($request->logo) {

            $fileName_ar = 'logo-white.' . request()->logo->getClientOriginalExtension();
            request()->logo->move(public_path('back/assets/global/images/logo/'), $fileName_ar);
            $array['logo'] = $fileName_ar;
        }
        // remove item null
        foreach ($array as $k => $ar) {
            if (!$ar)
                unset($array[$k]);
        }
        setting($array)->save();
        return redirect()->route('setting.index')
            ->with('flash_message',
                'Settings saved');
    }

}

resources/views/back/users/create.blade.php
@extends('back.layout.master')

@section('title', '| Add User')

@section('content')
    <div class="row">
        <div class='col-lg-4 col-lg-offset-4'>

            <h1><i class='fa fa-user-plus'></i> Add User</h1>
            <hr>

            {{ Form::open(array('route' => 'users.store')) }}

            <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                {{ Form::label('name', 'Name') }}
                {{ Form::text('name', '', array('class' => 'form-control')) }}
                <h6>The Name may not be greater than 30 characters.</h6>
            @if ($errors->has('name'))
                    <span class="text-danger">* {{ $errors->first('name') }}</span>
                @endif
            </div>

            <div class="form-group {{ $errors->has('email') ? ' has-error' : '' }}">
                {{ Form::label('email', 'Email') }}
                {{ Form::email('email', '', array('class' => 'form-control')) }}
                @if ($errors->has('email'))
                    <span class="text-danger">* {{ $errors->first('email') }}</span>
                @endif
            </div>

            <div class="form-group {{ $errors->has('website') ? ' has-error' : '' }}">
                {{ Form::label('website', 'Website') }}
                {{ Form::text('website', '', array('class' => 'form-control')) }}
                @if ($errors->has('website'))
                    <span class="text-danger">* {{ $errors->first('website') }}</span>
                @endif
            </div>

            <div class='form-group {{ $errors->has('roles') ? ' has-error' : '' }}'>
                {{ Form::label('roles', 'Roles') }}<br>
            @foreach ($roles as $role)
                    {{ Form::checkbox('roles[]',  $role->id ) }}
                    {{ Form::label($role->name, ucfirst($role->name)) }}<br>
                @endforeach
                    @if ($errors->has('roles'))
                        <span class="text-danger">* {{ $errors->first('roles') }}</span>
                    @endif
            </div>

            <div class="form-group {{ $errors->has('password') ? ' has-error' : '' }}">
                {{ Form::label('password', 'Password') }}<br>
                {{ Form::password('password', array('class' => 'form-control')) }}
                <h6>The password must be at least 6 characters.</h6>
            @if ($errors->has('password'))
                    <span class="text-danger">* {{ $errors->first('password') }}</span>
                @endif
            </div>

            <div class="form-group {{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                {{ Form::label('password', 'Confirm Password') }}<br>
                {{ Form::password('password_confirmation', array('class' => 'form-control')) }}
                @if ($errors->has('password_confirmation'))
                    <span class="text-danger">* {{ $errors->first('password_confirmation') }}</span>
                @endif
            </div>

            {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

            {{ Form::close() }}

        </div>
    </div>
@endsection

resources/views/back/users/edit.blade.php
@extends('back.layout.master')

@section('title', '| Edit User')

@section('content')
    <div class="row">

    <div class='col-lg-4 col-lg-offset-4'>

        <h1><i class='fa fa-user-plus'></i> Edit {{$user->name}}</h1>
        <hr>

        {{ Form::model($user, array('route' => array('users.update', $user->id), 'method' => 'PUT')) }}{{-- Form model binding to automatically populate our fields with user data --}}

        <div class="form-group  {{ $errors->has('name') ? ' has-error' : '' }}">
            {{ Form::label('name', 'Name') }}
            {{ Form::text('name', null, array('class' => 'form-control')) }}
            <h6>The Name may not be greater than 30 characters.</h6>
        @if ($errors->has('name'))
                <span class="text-danger">* {{ $errors->first('name') }}</span>
            @endif
        </div>

        <div class="form-group  {{ $errors->has('email') ? ' has-error' : '' }}">
            {{ Form::label('email', 'Email') }}
            {{ Form::email('email', null, array('class' => 'form-control')) }}
            @if ($errors->has('email'))
                <span class="text-danger">* {{ $errors->first('email') }}</span>
            @endif
        </div>

        <div class="form-group  {{ $errors->has('website') ? ' has-error' : '' }}">
            {{ Form::label('website', 'Website') }}
            {{ Form::text('website', null, array('class' => 'form-control')) }}
            @if ($errors->has('website'))
                <span class="text-danger">* {{ $errors->first('website') }}</span>
            @endif
        </div>

        <div class="form-group  {{ $errors->has('roles') ? ' has-error' : '' }}">
            {{ Form::label("roles","Roles")}}<br>
        @foreach ($roles as $role)
                {{ Form::checkbox('roles[]',  $role->id, $user->roles ) }}
                {{ Form::label($role->name, ucfirst($role->name)) }}<br>

            @endforeach
                @if ($errors->has('roles'))
                    <span class="text-danger">* {{ $errors->first('roles') }}</span>
                @endif
        </div>

        <div class="form-group  {{ $errors->has('password') ? ' has-error' : '' }}">
            {{ Form::label('password', 'Password') }}<br>
            {{ Form::password('password', array('class' => 'form-control')) }}
            <h6>The password must be at least 6 characters.</h6>
        @if ($errors->has('password'))
                <span class="text-danger">* {{ $errors->first('password') }}</span>
            @endif
        </div>

        <div class="form-group  {{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
            {{ Form::label('password', 'Confirm Password') }}<br>
            {{ Form::password('password_confirmation', array('class' => 'form-control')) }}
            @if ($errors->has('password_confirmation'))
                <span class="text-danger">* {{ $errors->first('password_confirmation') }}</span>
            @endif
        </div>

        {{ Form::submit('Update', array('class' => 'btn btn-primary')) }}

        {{ Form::close() }}

    </div>
    </div>
@endsection

resources/views/back/users/index.blade.php
@extends('back.layout.master')

@section('title', '| Users')

@section('content')
    <div class="row">

    <div class="col-lg-10 col-lg-offset-1">
        <h1><i class="fa fa-users"></i> User Administration </h1>
        <hr>
        <div class="table-responsive">
            <table class="table table-bordered table-striped">

                <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>User Roles</th>
                    <th>Operations</th>
                </tr>
                </thead>

                <tbody>
                @foreach ($users as $user)
                    <tr>

                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{  $user->roles()->pluck('name')->implode(' ') }}</td>{{-- Retrieve array of roles associated to a user and convert to string --}}
                        <td>
                            <a href="{{ route('users.edit', $user->id) }}" class="btn btn-info pull-left" style="margin-right: 3px;">Edit</a>

                            {!! Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $user->id],'class'=>'action' ]) !!}
                            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                            {!! Form::close() !!}

                        </td>
                    </tr>
                @endforeach
                </tbody>

            </table>
        </div>

        <a href="{{ route('users.create') }}" class="btn btn-success">Add User</a>

    </div>
    </div>
@endsection

resources/views/back/users/profile.blade.php
@extends('back.layout.master')

@section('title', '| Edit Profile')

@section('content')
    <div class="row">
        <div class='col-lg-4 col-lg-offset-4'>

            <h1><b>Your Profile</b></h1>
            {{ Form::open(array('route' => 'post-update-profile','files' => true)) }}

            <div class="form-group hidden">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <input type="hidden" name="_method" value="PATCH">
            </div>
            <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="email" class="control-label"><b>Name:</b></label>
                <input type="text" name="name" placeholder="Please enter your email here" class="form-control"
                       value="{{ $user->name }}"/>

                <?php if ($errors->has('name')) :?>
                <span class="help-block">
            <strong>{{$errors->first('name')}}</strong>
        </span>
                <?php endif;?>

            </div>
            <div class="form-group {{ $errors->has('email') ? ' has-error' : '' }}">
                <label for="email" class="control-label"><b>Email:</b></label>
                <input type="text" name="email" placeholder="Please enter your email here" class="form-control"
                       value="{{ $user->email }}"/>

                <?php if ($errors->has('email')) :?>
                <span class="help-block">
            <strong>{{$errors->first('email')}}</strong>
        </span>
                <?php endif;?>

                <div class="form-group {{ $errors->has('website') ? ' has-error' : '' }}">
                    <label for="website" class="control-label"><b>Website:</b></label>
                    <input type="text" name="website" placeholder="Please enter your website here" class="form-control"
                           value="{{ $user->website }}"/>

                    <?php if ($errors->has('website')) :?>
                    <span class="help-block">
            <strong>{{$errors->first('website')}}</strong>
        </span>
                    <?php endif;?>

            </div>
            <div class="form-group {{ $errors->has('password') ? ' has-error' : '' }}">
                <label for="email" class="control-label"><b>Password:</b></label>
                <input type="password" name="password" placeholder="Please enter your Password here" class="form-control"
                />

                <?php if ($errors->has('password')) :?>
                <span class="help-block">
            <strong>{{$errors->first('password')}}</strong>
        </span>
                <?php endif;?>

            </div>
            <div class="form-group {{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                <label for="password_confirmation" class="control-label"><b>Password Confirmation:</b></label>
                <input type="password" name="password_confirmation"
                       placeholder="Please enter your password_confirmation here" class="form-control"
                       value="{{ $user->password_confirmation }}"/>

                <?php if ($errors->has('password_confirmation')) :?>
                <span class="help-block">
            <strong>{{$errors->first('password_confirmation')}}</strong>
        </span>
                <?php endif;?>

            </div>
            <div class="form-group">
                <label for="avatar" class="control-label"><b>avatar:</b></label>
                <input type="file" name="avatar" class="form-control"/>
                <h6></h6>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default"> Submit</button>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
@endsection